change version

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,15 +46,37 @@ jobs:
     if: startsWith(github.ref, 'refs/tags/v')
     runs-on: self-hosted
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Set tag to env
-        run: |
-           if [[ "${{ github.ref }}" == refs/tags/* ]]; then
-            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
-           fi 
-      - name: Deploy to Kubernetes
-       
-        run: |
-          kubectl set image oviplokos/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ env.IMAGE_NAME }}:${{ env.TAG }} -n ${{ env.NAMESPACE }}
-          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: List files in the working directory
+      run: |
+        ls -la
+
+    - name: Extract version from tag or commit message
+      run: |
+        echo "GITHUB_REF: ${GITHUB_REF}"
+        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+          VERSION=${GITHUB_REF#refs/tags/}
+        else
+          VERSION=$(git log -1 --pretty=format:%B | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' || echo "")
+        fi
+        if [[ -z "$VERSION" ]]; then
+          echo "No version found in the commit message or tag"
+          exit 1
+        fi
+        VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
+        echo "Using version: $VERSION"
+        echo "VERSION=${VERSION}" >> $GITHUB_ENV
+
+    - name: Replace image tag in nginx.yaml
+      run: |
+        if [ ! -f ./nginx.yaml ]; then
+          echo "nginx.yaml not found in the current directory"
+          exit 1
+        fi
+        sed -i "s|image: oviplokos/nginx-diplom:.*|image: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}|" ./nginx.yaml 
+
+    - name: Apply Kubernetes manifests
+      run: |
+        kubectl apply -f ./nginx.yaml
